train_file: ['/home/chensishuo/data/coco/pretrain.json']



# size of vit model; base or large
vit: 'timesformer'
patch_size: 16
learnable_temporal_scaling: True
attention_type: 'divided_space_time'

vit_grad_ckpt: False
vit_ckpt_layer: 0


image_size: 224
batch_size: 24
num_frm_train: 2
max_words: 30
frm_sampling_strategy: 'headtail'

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 3000



